# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12c0d5d7fee58e1e1c7e82ed7eff3e5c2db8adc9a602d0fff04ae8da0393fab9357b6ce1f5906bc5b41197b963868408fa18f07b92e4966ba44714105604f024

test:
  secret_key_base: 0ae006c8ab9b4e0dbc20f14ac74d060bbcc533f81cbdd3539731ec916d78bfb54f92026939c96968e9b4e3de024efcd0515acd3f9bcf6dbc5e31b2c97e611ede

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
